### PR TITLE
added the email logo icon but it is not visible

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
Signed-off-by: Sambhav Gupta <sambhavgupta0705@gmail.com>

## Description

This PR fixes #

I tried adding the email icon to the footer section but it is not visible

## Testing

Please write instructions so we can verify your changes.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
#388

**Comment by chicken-biryani** [comment]
@Crystalsage ptal?

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Hi — Can you please signify what UI changes were caused via your PR?

**Comment by sambhavgupta0705** [comment]
HI ,there was no UI change via PR,but I was tryting to add email svg icon there.

**Pull request closed without merging**
