### PR TITLE
migration: Migrated PointOutput component from Vue 2 to Vue 3

### LINKED ISSUE #336: migration: migrate PointOutput to Vue 3 (Composition API)
- Migrate the [PointOutput.vue file](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/views/flint/PointOutput.vue) in src/views/flint/ to use CompositionAPI (check out https://github.com/moja-global/FLINT-UI/pull/311 PR by @Palaksharma23, or any other migration PR for reference.).
- Rename PointOutput.vue to PointOutputGraph.vue to make the name more descriptive.

If you have any questions or need help please reach out to me (or any other community member) here or on Slack.

### PR DESCRIPTION
**Pull request by Timonwa**
## Description
I have migrated the PointOutput.vue component from Vue 2 to Vue 3.
I also renamed the file from PointOutput.vue to PointOutputGraph.vue.
This closes #336

### CODE REVIEW

**Comment by Timonwa** [comment]
@YashKandalkar please review my changes.

**Comment by Timonwa** [comment]
@chicken-biryani can you help me check my pull request also? thank you.

**Review by chicken-biryani — APPROVED** [review]
Great work! Thank you for taking this up.

**Review by YashKandalkar — APPROVED** [review]
LGTM! :rocket: 
@Timonwa thanks for working on this!

**Pull request merged**
