### PR TITLE
fix: fixes hyperlinks of Twitter and YouTube

### LINKED ISSUE #389: [OSD] Bug: Incorrect hyperlinks in the footer
### Describe the bug.

Currently, we have some social media icons in the footer:
image

Unfortunately, the hyperlinks for Twitter and Youtube have been interchanged. 

### Describe the steps to reproduce the behavior.

1. Scroll down to the footer.
2. Click on Twitter icon - it should lead you to Youtube, and vice versa.

### Expected behavior.

Fix this behaviour by swapping the hyperlinks that the icons point to.

### Screenshots.

_No response_

### Operating Environment

Arch Linux, Firefox browser, API deployed on Azurewebsites, Latest commit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Description

This PR fixes #389 

### Change log

- Fixes hyperlinks of Twitter and YouTube by swapping them

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@Crystalsage kindly look into this!

**Review by chicken-biryani — APPROVED** [review]

**Review by Crystalsage — APPROVED** [review]
Thanks for working on this. We can merge this.

**Comment by abhilipsasahoo03** [comment]
Hi @Crystalsage is this going to be merged anytime soon?

**Comment by Crystalsage** [comment]
Hi @abhilipsasahoo03! 

We're sorry for the delay. I can't merge this personally because I'm just a contributor. 

Please merge this @chicken-biryani.

**Comment by abhilipsasahoo03** [comment]
> Hi @abhilipsasahoo03! 
> 
> We're sorry for the delay. I can't merge this personally because I'm just a contributor. 
> 
> Please merge this @chicken-biryani.

Oh, it's okay. Thanks for letting me know!

**Pull request merged**
