### PR TITLE
added accordian #113

### PR DESCRIPTION
**Pull request by Amishakumari544**
issue #113 # Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. 

## Testing

Please instructions so we can verify your changes.

If our automated tests fail, please feel free to reach out to us by leaving a comment down below and we will be happy to take a look

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Comment by Amishakumari544** [comment]
@sohamsshah  could you please review if its okay or not?

**Review by sohamsshah — CHANGES_REQUESTED** [review]
Hi @Amishakumari544 , good work. Though, there are some things that I would like to highlight for this implementation:
* The implementation isn't functional. Meaning, the component cannot be used as per user's input data.
* The open/close functionality for an Accordion is missing. The other accordion elements must toggle when one of them is expanded.
* For the Design API, we need to have components in such a way that is similar to:
```
<Accordion title="my title"> My Content <Accordion>
```
Feel Free to refer the following:
* [Slots in VueJS](https://vuejs.org/v2/guide/components-slots.html)
* [Accordion Using TailwindCSS in Vue](https://www.youtube.com/watch?v=vYEcJ7sIgJA)

In order to test this component, you can try importing it in Landing Page and check if it is functional. (We don't need to commit it, just for testing at the moment)

If you have any questions, please don't hesitate to ask; would be happy to help.

**Comment by Amishakumari544** [comment]
> Hi @Amishakumari544 , good work. Though, there are some things that I would like to highlight for this implementation:
> 
> * The implementation isn't functional. Meaning, the component cannot be used as per user's input data.
> * The open/close functionality for an Accordion is missing. The other accordion elements must toggle when one of them is expanded.
> * For the Design API, we need to have components in such a way that is similar to:
> 
> ```
> <Accordion title="my title"> My Content <Accordion>
> ```
> 
> Feel Free to refer the following:
> 
> * [Slots in VueJS](https://v3.vuejs.org/guide/component-slots.html#slots)
> * [Accordion Using TailwindCSS in Vue](https://www.youtube.com/watch?v=vYEcJ7sIgJA)
> 
> In order to test this component, you can try importing it in Landing Page and check if it is functional. (We don't need to commit it, just for testing at the moment)
> 
> If you have any questions, please don't hesitate to ask; would be happy to help.

Yes , you are right , I will do the changes.

**Comment by sohamsshah** [comment]
Hey @Amishakumari544 , as communicated by you regarding the unavailibility to work on this issue at the moment, I am closing this PR for now. But feel free to take up other issues and work on them. Thanks for working on the issue nonetheless :)

**Pull request closed without merging**
