### PR TITLE
feat: add Simulation Tour

### PR DESCRIPTION
**Pull request by YashKandalkar**
## Description
Adds a simulation tour modal for new users.

## Testing
Click on the (?) icon in Create Simulation page.

## Additional Context (Please include any Screenshots/gifs if relevant)

https://user-images.githubusercontent.com/35102959/189486190-c96c3576-1ffb-499b-b34f-f2561d58e3b1.mp4

### CODE REVIEW

**Comment by YashKandalkar** [comment]
@HarshCasper @Palaksharma23 @Janvi-Thakkar @chicken-biryani PTAL!

**Review by chicken-biryani — APPROVED** [review]

**Review by Janvi-Thakkar — COMMENTED** [review]
Hello @YashKandalkar, A lot of hardwork:) But I am not sure why I am facing this issue! Please have a look and let me know if it's only problem in my machine.

image

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar Ah. Thanks for catching this! Some styles from the UI Library project are leaking, this error is also because an img style from the BoxAlertStructure component is not scoped. I'll make a PR for it in the UI library repo and a temp fix here.

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar Ah. Thanks for catching this! Some styles from the UI Library project are leaking, this error is also because an img style from the BoxAlertStructure component is not scoped. I'll make a PR for it in the UI library repo and a temp fix here.

Maybe @Palaksharma23  or I faced it and then made it scoped or solved in another way, can't recall it right now. but sorry for the inconvenience!

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar No issues! It was just a small thing. Thanks!

**Review by Palaksharma23 — APPROVED** [review]
Amazing work :) @YashKandalkar! LGTM 🚀

**Pull request merged**
