### PR TITLE
refactor: updated datepicker in RothC configuration page with ant design

### PR DESCRIPTION
**Pull request by Timonwa**
# Pull Request Template

## Description
I updated the  RothC DatePicker Component in the [ConfigurationsRothC.vue](https://github.com/moja-global/FLINT-UI/issues/flint.ui%5Csrc%5Cviews%5Cflint%5CConfigurationsRothC.vue) file to use Ant Design Implementation. It was previously built with pure CSS implementation.
Fixes: #245 

## Testing
none

## Additional Context (Please include any Screenshots/gifs if relevant)
FireShot Capture 008 - moja global FLINT UI - localhost

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Can you please add a screenshot/GIF signifying your changes?

**Comment by Timonwa** [comment]
I have added a screenshot of the changes.

**Comment by SanjaySinghRajpoot** [comment]
Changes look good to me. 

Have you fixed the text alignment for the second line?

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Comment by Timonwa** [comment]
The text alignment has been fixed in pull request #251 by me. And was merged a dew hours ago. Once this is merged too, it will be aligned properly.

**Review by HarshCasper — APPROVED** [review]

**Comment by Timonwa** [comment]
Ok. I will do that.

**Pull request merged**
