### PR TITLE
Update RothC Configurations UI according to the new design

### LINKED ISSUE #183: Feature Request: Create a new Accordion Component Using Ant Design
### Is your feature request related to a problem? Please describe.

The current website has the Card component which needs to be changed with the Accordion component from the Ant Design. It has to be updated as per the new design. Drop down should work as expected along with the required fields. Dropdown

### Describe the solution you'd like.

Making a new Accordion component using Ant Design. Implementing it in the Vue.js file. 
Collapse - A content area that can be collapsed and expanded.
- Props for the heading Text
- Props for the Dropdown Text
- Props for Column Data 

Link - https://ant.design/components/collapse/

### Describe alternatives you've considered

_No response_

### Additional context.

Expected: 
Screenshot from 2022-03-16 12-06-07

### LINKED ISSUE #246: UI Update: RothC Parameter Configuration Page Redesign + Refactor
### Is your feature request related to a problem? Please describe.

Based on the new design:
image

All of the parameter configuration in the present implementation is in different routes. We need a single page form to input and test out RothC configuration interface. This issue focuses on UI side, api integration can be done in further PRs.

This would required refactoring the following:
- Update Routes files and delete unused files/components
- Redesign the whole UI with Ant Design and built-components in the design system
- Check for input validations and form filling of multiple fields in the project
- Re-confirm the fields with the team
- Remove all the css/tailwind related dependencies
- Convert to a single page.

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by YashKandalkar**
closes #183 and closes #246 
## Description
Updates the RothC configurations UI according to the proposed design. 

## Testing
Go to RothC configurations page to view the updated UI

## Additional Context (Please include any Screenshots/gifs if relevant)
image
image

### CODE REVIEW

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar @sohamsshah @SanjaySinghRajpoot PTAL!

**Comment by SanjaySinghRajpoot** [comment]
Thank you for the changes @YashKandalkar. Just want to ask you one thing you have moved all the RothC routes to a separate file. I guess if we keep all the API routes in one place it will be easier for us to keep track of different functions that are begin called by different routes. Like in this case you have transferred the routes to the `ConfigurationsRothC.vue` file. So we might have to change the Point routes as well so that the code remains consistent across the website. Please let me know your thoughts on this. 

Else the Changes look good to me.

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Comment by YashKandalkar** [comment]
Hey, @SanjaySinghRajpoot - RothC had sub-configurations which were on different views earlier. I have converted these views to components and imported them into the ConfigurationsRothC view as we wanted these configurations on the same page inside an accordion. Point does not have any configurations on different views. 
Although, now that we have the output table and graph on the same page as configurations, we can remove these routes as well:
```
'/flint/point_output_table',
'/flint/point_output',
'/flint/rothc_output_table',
'/flint/rothc_output'
```

**Review by Janvi-Thakkar — APPROVED** [review]
@YashKandalkar LGTM :))

**Comment by Janvi-Thakkar** [comment]
> Hey, @SanjaySinghRajpoot - RothC had sub-configurations that were on different views earlier. I have converted these views to components and imported them into the ConfigurationsRothC view as we wanted these configurations on the same page inside an accordion. Point does not have any configurations on different views. Although, now that we have the output table and graph on the same page as configurations, we can remove these routes as well:
> 
> ```
> '/flint/point_output_table',
> '/flint/point_output',
> '/flint/rothc_output_table',
> '/flint/rothc_output'
> ```

while creating the ant design table, I added it to the Point page as per the new design but I might have forgotten to remove the paths which I left there to test the table designs.

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar It's fine, we can create a new issue for removing the output paths.

**Pull request merged**
