### PR TITLE
Fix footer responsive design on smaller screen.

### PR DESCRIPTION
**Pull request by Timonwa**
## Description
 The Footer component was not responsive on smaller screens. the spaces on the left and right didn't align with the other components on the pages. 
closes issue #217

## Testing
You can view it on smaller screens.

### CODE REVIEW

**Comment by Timonwa** [comment]
@SanjaySinghRajpoot @Janvi-Thakkar  @YashKandalkar 
I saw the copyright has a different colour. do I leave it like that or change it to white like the rest of the text in the footer?

**Comment by SanjaySinghRajpoot** [comment]
Keep the same colour it is not meant to highlight on the footer. Rest all text has a different colour property so that it is easily visible to the user where they want to navigate. We don't have a separate page for copyright info. I hope this clear your doubt.

**Comment by Timonwa** [comment]
Ok. So everything should be color white right?

**Comment by YashKandalkar** [comment]
Hey - @Timonwa can we have the icon color match the background? The icons already have a white circle so a darker color would look better as an icon color. 
image
And also a tiny margin-right on the email icon would look better. The email can also be converted to an anchor tag for the email address. (You'll need to change the color of the email as it'll be a darker shade in the anchor tag)

**Review by sohamsshah — APPROVED** [review]
LGTM @Timonwa ! Thanks for the contribution 💯

(We can merge it after the UI changes are implemented as suggested by @YashKandalkar)

**Comment by Timonwa** [comment]
@SanjaySinghRajpoot @Janvi-Thakkar  @YashKandalkar 
I have made the necessary changes. The email is now a link, the icon colour is now the same colour as the background and the copyright paragraph is now colour white.
FireShot Capture 053 - moja global FLINT UI - localhost

**Review by YashKandalkar — APPROVED** [review]
@Timonwa LGTM! Thanks for the changes :rocket: 

@HarshCasper The auto-deployments are helping a lot, thanks for setting it up :smile:

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
