### PR TITLE
UI: removed sidebar

### LINKED ISSUE #105: Remove the Sidebar
Currently, we are motivated to restructure the FLINT-UI.
This issue is a piece of the puzzle.

**Todo**: 

**Comment out/Remove the Sidebar from the UI.**

image

### PR DESCRIPTION
**Pull request by himanshu007-creator**
# Pull Request Template

## Description

resolves #105 
Commented out the sidebar component

## Testing

Please instructions so we can verify your changes.

If our automated tests fail, please feel free to reach out to us by leaving a comment down below and we will be happy to take a look

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Review by sohamsshah — CHANGES_REQUESTED** [review]
Hey @himanshu007-creator , can you please remove the commented out code? Also, we won't need the `Sidebar` component; which can also be safely deleted. Make sure, it doesn't break other pages. Also, post a snapshot of the updated `FLINT.vue` layout page.

**Comment by chicken-biryani** [comment]
Hey, @himanshu007-creator how are things coming up?

If you're having any trouble, please feel free to reach out.

**Comment by himanshu007-creator** [comment]
> Hey, @himanshu007-creator how are things coming up?
> 
> If you're having any trouble, please feel free to reach out.

Hey, I have exams so wasn't much active. I will do the above-mentioned thing soon

**Comment by HarshCasper** [comment]
Hi @himanshu007-creator 

The Docker build is broken, so you don't have to worry about that. Let us know once it is ready to review.

**Comment by himanshu007-creator** [comment]
> Hey @himanshu007-creator , can you please remove the commented out code? Also, we won't need the `Sidebar` component; which can also be safely deleted. Make sure, it doesn't break other pages. Also, post a snapshot of the updated `FLINT.vue` layout page.

Hey, <code>Sidebar</code> component is also being used <a href="https://github.com/moja-global/FLINT-UI/blob/58d08392c57e56bf55c81d0f4bfaeac756864b21/flint.ui/src/layouts/GCBM.vue">here </a>. Shall i remove the import and usage here as well?!

**Comment by chicken-biryani** [comment]
@himanshu007-creator Yes yes. The aim is to remove the sidebar wherever it's used.

**Comment by chicken-biryani** [comment]
@himanshu007-creator kindly let us know when the PR is ready to review.

**Comment by HarshCasper** [comment]
@himanshu007-creator Please rebase against the master branch to fix the CI.

**Comment by sohamsshah** [comment]
Hey @HarshCasper , I guess this PR is good to be merged.

**Pull request merged**
