### PR TITLE
Added header for the `GCBM` Page

### LINKED ISSUE #170: Feature Request: Adding header for the `GCBM` Page
### Is your feature request related to a problem? Please describe.

`GCBM` page does not have any header or footer. 

### Describe the solution you'd like.

- Adding a header component for the `GCBM` page. 
- Fixing basic UI errors on the `GCBM` page
- Trying to maintain consistency across the website.

### PR DESCRIPTION
**Pull request by SanjaySinghRajpoot**
# Pull Request Template
Fixes #170 

## Description
- Adding header component to the `GCBM` page of the website. 
- Removed gradient property 
- Fixed small bug for the `rothc` page 

## Changes

Screenshot from 2022-03-11 17-48-43

Thank You

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@SanjaySinghRajpoot can you please add a video/picture of what change you've done.

Thanks.

**Comment by SanjaySinghRajpoot** [comment]
I have updated the above description please check @chicken-biryani

**Comment by chicken-biryani** [comment]
@YashKandalkar @sohamsshah can you please have a look? :)

**Review by YashKandalkar — CHANGES_REQUESTED** [review]
Hey @SanjaySinghRajpoot thanks for the PR! 
Just a few suggestions:
For configurations/rothc:
- the padding-x of the inner contents is less (check the padding-x of configurations/point)
- there is no padding bottom on the Run button
- the 2nd line in the desc. (Input the custom values in the fields bel... ) isn't of a smaller size in the new design.
- the heading "Configure Parameters" should be of the earth color

In gcbm/dashboard:
- there are these prettier warnings which you can fix:
image
- Can you make the `src/layouts/GCBM.vue` file similar to `src/layouts/FLINT.vue`? Make the classes of those 2 divs from GCBM.vue the same as FLINT.vue so the margin left is removed. (also check if this breaks the UI in some way)

**Comment by SanjaySinghRajpoot** [comment]
Hello, @YashKandalkar  In this PR have only added the header component to the `GCBM` page. I will make other changes in a separate PR, for now, I have fixed all the warnings in the code. I have also modified the `src/layouts/GCBM.vue` as requested. 

Thank You

**Review by sohamsshah — APPROVED** [review]
Thanks a lot @SanjaySinghRajpoot . This looks good for now. For the future changes, let's continue refactoring to Ant Design; though currently it is a good addition to the project.

**Pull request merged**
