### PR TITLE
fix : other sliders shaking on value change

### PR DESCRIPTION
**Pull request by RamGoel**
# Pull Request Template

### Problem 
Issue Fixed (#265) 
When the value of slider changes then it moves the other sliders, like "234" has more width than "28".

### Solution
Gave a fixed width (lets say 32 units) to all Sliders using w-32 (divs with flex-grow class) on flint.ui\src\views\flint\ConfigurationsPoint.vue (Line 32)

### CODE REVIEW

**Comment by RamGoel** [comment]
@Janvi-Thakkar please have a look

**Comment by RamGoel** [comment]
@HarshCasper It'll be great if you can help me merge this PR.

Thank you

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar ptal

**Comment by HarshCasper** [comment]
Please fix the lint issues here: https://github.com/moja-global/FLINT-UI/actions/runs/3217191636/jobs/5259878123

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Can you please resolve the merge conflicts?

**Comment by Janvi-Thakkar** [comment]
@RamGoel Can you please resolve the lint error?

**Comment by Janvi-Thakkar** [comment]
@RamGoel kindly resolve the merge conflicts!

**Pull request closed without merging**
