### PR TITLE
Integrated DatePicker component from uI library in Point and RothC

### LINKED ISSUE #357: Feature Request: Replace ant-dv datepicker by ui-library datepicker in Point and RothC
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by Janvi-Thakkar**
## Description
Integrated DatePicker component from uI library in Point and RothC

This PR Fixes #357 

## Additional Context (Please include any Screenshots/gifs if relevant)
image
image

### CODE REVIEW

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani @YashKandalkar @HarshCasper can you please review this?

**Review by chicken-biryani — APPROVED** [review]

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar the date-picker doesn't close when clicked outside, will this be worked upon later?

**Comment by Janvi-Thakkar** [comment]
Hello 

> @Janvi-Thakkar the date-picker doesn't close when clicked outside, will this be worked upon later?

@YashKandalkar, Thank you for pointing this out. I have also observed my mistake in this. 

I made the input field **disabled** instead of **readonly**. due to which whenever you open date picker by clicking in the input area, you will not be able to close it by clicking outside. The blur property won't work because of **disabled** attribute. But if you click on the SVG icon and open the date picker, you will be able to close it from outside.

I have done those changes in my local project but have yet to raise the PR. Those changes will be released in the next version of the package.

**Comment by Janvi-Thakkar** [comment]
@Palaksharma23 @YashKandalkar can it be merged?

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
