### PR TITLE
Refactor home landing page

### LINKED ISSUE #263: Bug: Content of Homepage content not aligned properly and over flows on smaller screen
### Describe the bug.

1. When the homepage is viewed on screens smaller than 375px, the main content overflows from its container.
2. on medium-size screens, the main content and the banner content do not have the same padding/margin.

### Describe the steps to reproduce the behaviour.

View the homepage on different screen sizes

### Expected behaviour.

The banner and main content are supposed to have the same padding/margin and width. and its contents are not supposed to overflow its container.

### Screenshots.

flint-hompage320px

image2

### Operating Environment

Windows 10.

### Additional Information

Can I work on this issue?

### PR DESCRIPTION
**Pull request by Timonwa**
# Pull Request Template

## Description
Fixed the content of the Homepage content that was not aligned properly and overflowed on smaller screens.
closes #263 

## Additional Context (Please include any Screenshots/gifs if relevant)
FireShot Capture 013 - moja global FLINT UI - localhost
FireShot Capture 016 - moja global FLINT UI - localhost

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar @SanjaySinghRajpoot @YashKandalkar can you please have a look?
I hope there aren't duplicates.

**Comment by Timonwa** [comment]
@Akronix There is an open issue already on it concerning the padding for the footer. and it has been assigned to someone . Once I finish working on my present pull request and the footer still hasn't been fixed by then, I will ask if the issue can be assigned to me and work on it.

**Comment by padmajabhol** [comment]
I believe you are trying to fix the overflowing in smaller screen sizes here. Although the card layout in large screen has changed a bit where it occupies a lot more area than it previously did, can you bring it back how it was previously? Rest of the things are good to go!

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar @SanjaySinghRajpoot @YashKandalkar can you please have a look? I hope there aren't duplicates.

@chicken-biryani Will do by tomorrow

**Comment by Timonwa** [comment]
> I believe you are trying to fix the overflowing in smaller screen sizes here. Although the card layout in large screen has changed a bit where it occupies a lot more area than it previously did, can you bring it back how it was previously? Rest of the things are good to go!

Ok @padmajabhol . I will check it out and work on it tomorrow.

**Comment by Timonwa** [comment]
> I believe you are trying to fix the overflowing in smaller screen sizes here. Although the card layout in large screen has changed a bit where it occupies a lot more area than it previously did, can you bring it back how it was previously? Rest of the things are good to go!

hi @padmajabhol, I have fixed the width. it now has a fixed width on larger screens.
homepage-card

**Comment by Timonwa** [comment]
good day, I have added justify-content: "space-between" to the cards.
@SanjaySinghRajpoot @Janvi-Thakkar @YashKandalkar 
FireShot Capture 040 - moja global FLINT UI - localhost

**Comment by Timonwa** [comment]
good day, I have added justify-content: "space-between" to the cards.
@SanjaySinghRajpoot @Janvi-Thakkar @YashKandalkar 
FireShot Capture 040 - moja global FLINT UI - localhost

**Review by Janvi-Thakkar — APPROVED** [review]
@Timonwa Thanks for the quick fix! LGTM:)

**Review by YashKandalkar — APPROVED** [review]
Hey, @Timonwa
Thanks for working on this :rocket:
LGTM!

**Pull request merged**
