### PR TITLE
replaced navbar component

### LINKED ISSUE #383: Feature Request: Change current Navbar with UI-library's Navbar component
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered

_No response_

### Additional context.

reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-navbar--primary-with-other-components

### PR DESCRIPTION
**Pull request by rahulsh18**
Signed-off-by: rahulsh18 <rahulsharmaa1805@gmail.com>

## Description

Replaced current Navbar component with UI Library's Navbar. This PR fixes #383 

## Additional Context (Please include any Screenshots/gifs if relevant)

image

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @rahulsh18 I'm unable to access the navbar content on mobile view.

**Comment by rahulsh18** [comment]
hi @abhilipsasahoo03 , thanks for pointing it out. I've fixed that in the recent commits.

**Comment by abhilipsasahoo03** [comment]
> hi @abhilipsasahoo03 , thanks for pointing it out. I've fixed that in the recent commits.

Yes it's working now! :) Thank you!

**Comment by HarshCasper** [comment]
Hi @rahulsh18 — Can you please resolve the conflicts so that I can merge it? Thanks :)

**Review by Palaksharma23 — APPROVED** [review]

**Comment by HarshCasper** [comment]
Hi @rahulsh18 — Any updates on the merge conflicts? If you can kindly resolve them, that would be great :)

**Comment by rahulsh18** [comment]
hey @HarshCasper i've resolved the conflict locally

**Comment by Janvi-Thakkar** [comment]
> hey @HarshCasper i've resolved the conflict locally

Hi @rahulsh18, Please commit it so that the PR can be merged.

**Pull request closed without merging**
