### PR TITLE
Imported Footer to the `RothC`,`Point` and `GCBM` Page

### LINKED ISSUE #184: Feature Request: Importing Footer to the `RothC`,`Point` and `GCBM` Page
### Is your feature request related to a problem? Please describe.

Currently, only the main page has the new header component. Other pages are still missing the Footer component. 

### Describe the solution you'd like.

I will import the footer component to all 3 pages. A few changes have to done to make the UI look clean. 

### Describe alternatives you've considered

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by SanjaySinghRajpoot**
Fixes #184

## Description

- Added Footer component to the `RothC`,`Point` and `GCBM` Page. 
- Fixed CSS properties for better UI.

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@sohamsshah and @YashKandalkar can you please have a look?

**Review by YashKandalkar — CHANGES_REQUESTED** [review]
Hi @SanjaySinghRajpoot ! Thanks for the PR.
The footer looks good but is the background color correct? The grayish bg-color doesn't really look good with white text. What do you think? 
image

**Comment by chicken-biryani** [comment]
@YashKandalkar I agree. Maybe we can ask someone in the #user-interface channel for design-advice

**Comment by YashKandalkar** [comment]
hey @chicken-biryani since @SanjaySinghRajpoot is just importing the Footer component which was created in a previous PR, I think we should create another issue for fixing the colors of footer, after discussing on Slack of course.
What do you think?

**Comment by chicken-biryani** [comment]
@YashKandalkar absolutely!

**Comment by SanjaySinghRajpoot** [comment]
Yes, let's keep this PR for importing the footer later I will make another issue to update the Footer component. We can take some inspiration from Community Website.

**Comment by padmajabhol** [comment]
Hi. I kept it similar to the footer present in https://moja.global/ , so we can have some sort of uniformity?

**Review by padmajabhol — APPROVED** [review]

**Review by sohamsshah — APPROVED** [review]
LGTM @SanjaySinghRajpoot , thanks for the PR!

I see there are some other tailwind-related changes apart from the Footer import, can you brief about them?
 
@padmajabhol has implemented footer in #168 (components/footer), we can keep that consistent across all our views in successive PRs.

**Comment by SanjaySinghRajpoot** [comment]
@sohamsshah yes there are some width and height changes as the `Footer` component has to be of full width, those changes are done so that the footer is end to end. 

Thank You

**Comment by sohamsshah** [comment]
> @sohamsshah yes there are some width and height changes as the `Footer` component has to be of full width, those changes are done so that the footer is end to end.
> 
> Thank You

Makes sense. Thanks for the contribution!

**Pull request merged**
