### PR TITLE
Refactor date picker point

### PR DESCRIPTION
**Pull request by Timonwa**
# Pull Request Template

## Description
I updated the Point DatePicker Component in the [ConfigurationsPoint.vue](https://github.com/moja-global/FLINT-UI/issues/flint.ui%5Csrc%5Cviews%5Cflint%5CConfigurationsPoint.vue) file to use Ant Design Implementation. It was previously built with pure CSS implementation.
Fixes: #244

## Testing
none

## Additional Context (Please include any Screenshots/gifs if relevant)
FireShot Pro Webpage Screenshot #001 - 'moja global FLINT UI' - localhost

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@YashKandalkar @SanjaySinghRajpoot @Janvi-Thakkar

**Comment by Janvi-Thakkar** [comment]
@Timonwa @chicken-biryani I feel like this https://github.com/moja-global/FLINT-UI/pull/222 is similar. Can you please confirm?

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar yes. I believe some issues have been duplicated.

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani I think in PR of [joharikushagra](https://github.com/joharikushagra) regarding the same he worked on width and hover effect as well as per design. So, I am confused about whether to go with this PR or that one?

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar We can go with this one. Even though he has done some great work. The changes that were to be made 5 days ago haven't been made, yet.

He may be busy elsewhere.

**Review by Janvi-Thakkar — APPROVED** [review]

**Pull request merged**
