### PR TITLE
feat: Replaced DatePicker component instances in Datepicker.vue

### LINKED ISSUE #396: [OSD] Feature Request: Replace current DatePicker component with UI-library's DatePicker component - DatePicker
### Describe the solution you'd like.

Replace all of the DatePicker component instances in `DatePicker.vue` only.

### Additional context.

The current Datepicker component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

[image

Current datepicker component reference: https://www.antdv.com/components/date-picker
UI-library notification reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-datepicker--mandatory-prop
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Description

This PR fixes #396 

### Change log

- Replaces all of the current DatePicker component instances in ``Datepicker.vue`` with UI-library's DatePicker component

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@chicken-biryani kindly review

**Review by chicken-biryani — COMMENTED** [review]
Lgtm! @abhilipsasahoo03 can you sign the DCO bot.

**Comment by chicken-biryani** [comment]
@Crystalsage can you have a look?

**Comment by abhilipsasahoo03** [comment]
> Lgtm! @abhilipsasahoo03 can you sign the DCO bot.

Hi @chicken-biryani I'm unable to sign the DCO as I'm facing some bugs in the GitHub CLI :( I'll have to look into that.

**Comment by chicken-biryani** [comment]
@abhilipsasahoo03 its okay. Take your time.

You have to run these commands.

`` git commit --amend --no-edit --signoff
 git push --force-with-lease origin master
``
Also, I beleive you forgot to create a different branch... Because I can see the doc commit. You may want to rebase?

**Review by Crystalsage — CHANGES_REQUESTED** [review]
Thanks for the PR @abhilipsasahoo03! LGTM :)

As @chicken-biryani suggested, please consider doing a rebase to avoid having merge commits in your PR. Also, please make sure the PR is related to the scope of the issue. Feel free to make another PR for the issue with the docs.

**Comment by abhilipsasahoo03** [comment]
Hi @chicken-biryani I have signed off, rebased and force pushed! Please look into it!

**Comment by abhilipsasahoo03** [comment]
> Thanks for the PR @abhilipsasahoo03! LGTM :)
> 
> As @chicken-biryani suggested, please consider doing a rebase to avoid having merge commits in your PR. Also, please make sure the PR is related to the scope of the issue. Feel free to make another PR for the issue with the docs.

Okay, I'll keep that in mind!

**Comment by chicken-biryani** [comment]
Aah! @abhilipsasahoo03 

You may want to rebase, again?

**Comment by chicken-biryani** [comment]
Please feel free to text @Crystalsage if you need help.

**Comment by abhilipsasahoo03** [comment]
Hey @chicken-biryani I'm pretty confused about what to do from here. I tried to sign off the only unsigned commit using steps provided by DCO. Should I rebase again with a signoff or just close this PR and create a new one?

**Comment by chicken-biryani** [comment]
@abhilipsasahoo03 you signed the bot. (Yay)

But if you check the files that have been changed it's 56 files and that's because the commit history. That's okay!

You can close this PR and open a new one. Be careful with the branching.

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 you signed the bot. (Yay)
> 
> But if you check the files that have been changed it's 56 files and that's because the commit history. That's okay!
> 
> You can close this PR and open a new one. Be careful with the branching.

Okay sure!

**Pull request closed without merging**
