### PR TITLE
feat: update landing page UI according to the new design

### LINKED ISSUE #155: Feature Request: update the landing page of Flint UI according to the new design
### Is your feature request related to a problem? Please describe.

The current landing page of Flint UI is not in accordance with the [new design](https://www.figma.com/proto/JXB1KKGWxD2dLR7dx2hqWS/Flint-UI?node-id=3%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A2).

There are some things that needs to be changed:
- The font currently being applied is Roboto but should me DM Sans.
- The landing banner is not of the correct height (has more padding than needed), 
- The landing text is not of the correct size
- The font color and line height in the 3 LandingPageCard components are not according to the new design.
- The Button component created in [this](https://github.com/moja-global/FLINT-UI/issues/111) PR can be used instead of the current "Explore" button (router link).

### Describe the solution you'd like.

Most of the issues require some style changes, and the Button component can be imported in [LandingPageCard.vue](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/components/Cards/LandingPageCard.vue) and used for redirecting to the appropriate link (with a new onClick method)

### Describe alternatives you've considered

-

### Additional context.

Current UI of landing page:
image

UI after making changes:
image

Similar changes can be made to the banner to match the new design.

### PR DESCRIPTION
**Pull request by YashKandalkar**
## Description

 The UI changes requires as per the [new design](https://www.figma.com/proto/JXB1KKGWxD2dLR7dx2hqWS/Flint-UI?node-id=3%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A2) were made.

- The global font famity (DM Sans) was shifted from index.html to index.css, and `!important` was added because the font was not being applied. I don't completely understand why, but some other library might have added `Roboto, ...` as font family which takes higher precedence. `!important` solved this.
- The Button component made according to the new design was used.
- The landing banner and project's description had issues (padding of text, responsive text size, etc.)
- Navbar text color was changed acc. to the new design.
- LandingPageCard also had some styling issues which were fixed

## Testing

The UI changes can be seen by running `yarn serve` and opening the landing page.

## Additional Context (Please include any Screenshots/gifs if relevant)
image
image

Fixes #155 

Let me know if there are any changes required!

### CODE REVIEW

**Comment by YashKandalkar** [comment]
Hey @chicken-biryani, @sohamsshah can you have a look at this? Tell me if there are any changes required!

**Comment by chicken-biryani** [comment]
Lgtm!

**Review by chicken-biryani — APPROVED** [review]

**Comment by chicken-biryani** [comment]
@iamrajiv can you please review this PR?

**Comment by pragyamittal0** [comment]
Hi, I am Pragya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Review by sohamsshah — APPROVED** [review]
LGTM!

**Pull request merged**
