### PR TITLE
Add feature: Display Point & RothC output

### PR DESCRIPTION
**Pull request by shubhamkarande13**
## Description

Displays the received Point and RothC outputs as a grid/spreadsheet.

Introducing [RevoGrid](https://revolist.github.io/revogrid/) for rendering the outputs as a spreadsheet.

https://user-images.githubusercontent.com/13800316/129945924-53bfe6b4-b817-45ed-94ce-ecad137e20aa.mp4

### CODE REVIEW

**Comment by aornugent** [comment]
Great start! I'm interested to see it with real data. :100:

**Comment by shubhamkarande13** [comment]
@aornugent I've noticed that `point.results` and `rothc.results` point to the exact same variable `results` in the store, and hence when I run the Point module, the RothC result also gets updated. So the modular approach of the state is just for readability, and doesn't actually isolate all the different variables. 
Can we go back to using different names for all state variables?

**Comment by shubhamkarande13** [comment]
@waridrox could you please test to check if the configuration is broken or not? Everything seems fine at my end.

**Comment by shubhamkarande13** [comment]
Please have a look at the feature demo in the first comment!

**Comment by aornugent** [comment]
Great work @shubhamkarande13! A few thoughts:
* that's disappointing our module namespacing isn't working correctly. It might be that we need to be more selective about how we load the Vuex modules. Please file an issue describing how the code works now and how it's intended to work.
* the table is a little hard to read, it probably needs a white background and some borders. It's unusual to have it take up the whole page for just a few comments. Again, if you're not interested in fixing it in this PR, then leave a comment on #4 for future reference.
* somehow your GCBM changes on #54 have made it into this PR, please remove them.

**Comment by shubhamkarande13** [comment]
@aornugent could you please review the PR once again? I tried to drop the GCBM job commit from this branch. 😅

@waridrox could you please beautify the tables a bit as suggested by @aornugent ? I'm bad at design. 😂

Thank you both! 🤗❤️

**Comment by waridrox** [comment]
Here's the preview for modified implementation. The state updation from vuex could be referenced later, though it is a crucial thing to worry about 😕 - https://michaelnthiessen.com/debugging-guide-why-your-component-isnt-updating/


https://user-images.githubusercontent.com/58583793/130188103-9162dfff-460a-4514-a5ee-638085a35059.mov

**Comment by aornugent** [comment]
@waridrox - agreed, it's important. I like the mapState / mapGetters pattern in the link you shared above. I believe this can be used to handle modules that share similar names, but I don't yet understand why we have conflict given that our modules are isolated within components.

Is it true that `store/point.js` is only loaded in `point` components (and `store/rothc.js` is only loaded in `rothc` components) or are they being invoked at a higher level that causes a namespace collison?

This PR is looking good for now, so let's file an issue to continue the namespace discussion after we merge.

**Review by aornugent — APPROVED** [review]

**Review by chicken-biryani — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
