### PR TITLE
fix: difference in hover effects of button

### PR DESCRIPTION
**Pull request by void-hr**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. 

## Testing

Please instructions so we can verify your changes.

If our automated tests fail, please feel free to reach out to us by leaving a comment down below and we will be happy to take a look

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Comment by void-hr** [comment]
Before

beforea

163649175-9b92878d-cbf2-4d8a-b34e-939c7a0db3ef


After

moja global FLINT UI and 2 more pages - Personal - Microsoft​ Edge 17-04-2022 19_47_30
moja global FLINT UI and 2 more pages - Personal - Microsoft​ Edge 17-04-2022 19_48_18

**Review by Palaksharma23 — APPROVED** [review]

**Comment by Palaksharma23** [comment]
@void-hr Please link the pull request to the issue it solves :)

**Comment by void-hr** [comment]
> @void-hr Please link the pull request to the issue it solves :)

I am on it. Thanks!

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar please take a look as well.
Thanks, @Palaksharma23 for your efforts.

**Review by Janvi-Thakkar — COMMENTED** [review]
@void-hr Thanks for the PR! Please change hover effects in GCBMUpload.vue and GCBMRun.vue for step 2 and step 3 of GCBM workflow. 

Also, maybe by mistake you shifted "@tailwind utilities". Please put it as before.

**Review by sohamsshah — APPROVED** [review]
LGTM! @void-hr Thanks for the PR!

**Comment by void-hr** [comment]
@Janvi-Thakkar could you please review my PR. I have updated the GCMB files

**Review by Janvi-Thakkar — APPROVED** [review]

**Pull request merged**
