### PR TITLE
feat: replaced notification component with Moja Global UI library

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
Signed-off-by: Sambhav Gupta <sambhavgupta0705@gmail.com>

## Description
Changing the notification library to UI library

This PR fixes #

#393 

## Testing

Please write instructions so we can verify your changes.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Comment by Janvi-Thakkar** [comment]
Hi @sambhavgupta0705, Thanks for working on this. Please revert the changes for yarn.lock file and do not commit this file from now onwards.

**Comment by sambhavgupta0705** [comment]
Hi @Janvi-Thakkar  I removed one yarn.lock but unable to remove the another one,can you please help me with that

**Comment by Janvi-Thakkar** [comment]
> Hi @Janvi-Thakkar I removed one yarn.lock but unable to remove the another one,can you please help me with that

Hi @sambhavgupta0705, sorry I didn't get you. There was only one yarn.lock file in the commit.

**Comment by sambhavgupta0705** [comment]
Hi @Janvi-Thakkar I tried removing the yarn.lock but wasn't successful.Sorry but I created a new PR with only necessary changes it .Kindly please review it.
mentioning it here #441

**Pull request closed without merging**
