### PR TITLE
fix RothC output 

### PR DESCRIPTION
**Pull request by YashKandalkar**
## Description
RothC output was not properly visible.

## Testing
Go to RothC config, click Run, then RothC Output Table.

## Additional Context (Please include any Screenshots/gifs if relevant)
image
image

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Thank you so much for this.

**Comment by YashKandalkar** [comment]
@chicken-biryani No problem! :smile: 
Also, can you send me the commands to fix the DCO bot's checks, please? I'll save it somewhere this time :)
Thanks!

**Comment by chicken-biryani** [comment]
It feels illegal telling you this but nowwww you can click on "Set dco to pass" after clicking on the check details.

Here's the commands:

`` git commit --amend --no-edit --signoff
 git push --force-with-lease origin master``

**Comment by YashKandalkar** [comment]
@chicken-biryani Haha thanks!

**Comment by YashKandalkar** [comment]
@SanjaySinghRajpoot @Janvi-Thakkar @sohamsshah PTAL!

**Comment by SanjaySinghRajpoot** [comment]
Changes look good to me. Just had a small doubt does `console.log` was removed for a reason?

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Comment by YashKandalkar** [comment]
@SanjaySinghRajpoot They were logging the same thing on the console

**Review by HarshCasper — APPROVED** [review]
Thanks!

**Pull request merged**
