### PR TITLE
PR template improved

### LINKED ISSUE #371: PR templated needs improvement
### What is the current documentation state?

_No response_

### Where is this stated?

_No response_

### Why do you want to improve the statement?

image
 
1> The heading looks too vague , If we are filing a PR request , theres no need of it.

2> there are many lines which can be commented to save space and look proffessional.

3> No mention of this PR fixes what ? which lets to unlinking of PR's to issues mainly for new comers.

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by legendarykamal**
# Pull Request Template

## Description
Fixes #371 
Please include a summary of the change and which issue is fixed. 

## Testing

Please instructions so we can verify your changes.

If our automated tests fail, please feel free to reach out to us by leaving a comment down below and we will be happy to take a look

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Comment by legendarykamal** [comment]
@chicken-biryani can you please review this one :thinking:

**Comment by chicken-biryani** [comment]
@legendarykamal looks good. Can you please sign the DCO?

**Review by chicken-biryani — APPROVED** [review]

**Comment by legendarykamal** [comment]
> @legendarykamal looks good. Can you please sign the DCO?

thankyou @chicken-biryani yes I will :)

**Comment by legendarykamal** [comment]
done @chicken-biryani , its ready to merge :)

**Review by chicken-biryani — APPROVED** [review]

**Review by YashKandalkar — APPROVED** [review]

**Pull request merged**
