### PR TITLE
Button span fix

### PR DESCRIPTION
**Pull request by RamGoel**
# Pull Request Template

## Description
Fixes Issue (#366)
Fixed the Button splitting to Multiple Lines

### Before Fix

flint-ui vercel app_flint_configurations_point (2)

### After Fix

flint-ui vercel app_flint_configurations_point (1)

### CODE REVIEW

**Review by Palaksharma23 — APPROVED** [review]
Thanks @RamGoel for working on this! 
LGTM 🚀

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Review by HarshCasper — APPROVED** [review]

**Comment by legendarykamal** [comment]
if these are approved , why are we not merging these @HarshCasper ?

**Comment by YashKandalkar** [comment]
Hey, @RamGoel Sorry for the late response on this! Could you please pull the latest changes and fix the lint error?
Thanks for working on this!

**Comment by RamGoel** [comment]
@YashKandalkar Seems Fine to me Now. Check Once.

**Comment by HarshCasper** [comment]
Hi @RamGoel — The lint errors still persist. Please see this and fix them: https://github.com/moja-global/FLINT-UI/actions/runs/3217115877/jobs/5259725184

**Comment by RamGoel** [comment]
Hi @HarshCasper , I am unable to solve these errrors. could you please guide me.

**Comment by YashKandalkar** [comment]
@RamGoel just execute `yarn lint --fix` inside the project folder in a terminal.

**Pull request merged**
