### PR TITLE
Resolves issue#195

### PR DESCRIPTION
**Pull request by ps-19**
# Pull Request Template

## Description

The PR resolves issue #195

## Testing

No tests  are failing.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

### CODE REVIEW

**Review by chicken-biryani — COMMENTED** [review]
I believe @aniketh-varma is already working on the issue.

Please cross check with him if he's working on it right now. If not- 

Do changes --

Can you remove the content and just link it to the already existing Code of conduct.

Should look something like-

"**Code of conduct**
Have a look at our code of conduct.

**Comment by ps-19** [comment]
@chicken-biryani done

**Comment by chicken-biryani** [comment]
@ps-19 looks great.

I am still not sure if it's ok to merge since @aniketh-varma was working on it.
If he doesn't respond and has stalled the issue I'll merge this one.

**Review by chicken-biryani — APPROVED** [review]

**Comment by aniketh-varma** [comment]
Hi @chicken-biryani, Yes I was working on the issue, had to make a few changes in the PR I made previously.

**Comment by chicken-biryani** [comment]
@aniketh-varma can you do them. Just modify the wordings in your PR a little. And then I think it's good to go.

**Comment by aniketh-varma** [comment]
@chicken-biryani Sure I will update the same.

**Comment by sohamsshah** [comment]
Hi @aniketh-varma , please let me know if you need any help in solving the issue.

**Comment by aniketh-varma** [comment]
> Hi @aniketh-varma , please let me know if you need any help in solving the issue.

Hi @sohamsshah, the issue has been resolved. Please check #195

**Pull request closed without merging**
