### PR TITLE
feat : Replaced accordion component with Ui-library's

### LINKED ISSUE #384: Feature Request: Replace current accordion component with UI-library's accordion component
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered

_No response_

### Additional context.

The current accordion can be found at: https://flint-ui.vercel.app/flint/configurations/rothc
Ui-library accordion reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-accordion--primary
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

### PR DESCRIPTION
**Pull request by thisiskaransgit**
## Description

This PR fixes #384 

Replaced the  current accordion component with UI-library's accordion component

## Testing
Changes are visible at : /flint/configurations/rothc

## Additional Context (Please include any Screenshots/gifs if relevant)
Screenshot from 2022-09-23 00-59-21
Screenshot from 2022-09-23 01-00-05

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
@Janvi-Thakkar Kindly review the PR

**Comment by Janvi-Thakkar** [comment]
image

**Comment by Janvi-Thakkar** [comment]
@thisiskaransgit Please add margins as per requirements!

**Comment by thisiskaransgit** [comment]
If you are referring to the overlapping, This issue is fixed with #411
Screenshot from 2022-09-25 22-25-39

**Review by Janvi-Thakkar — APPROVED** [review]
LGTM @thisiskaransgit :)

**Review by YashKandalkar — APPROVED** [review]
Awesome work @thisiskaransgit :rocket: 
Thanks for working on this!

**Pull request merged**
