### PR TITLE
Feat : migrated component to Vue 3 (Composition API)

### PR DESCRIPTION
**Pull request by thisiskaransgit**
# Pull Request Template

## Description

 **FIxed issue: #337** 

**1. migrated RothCOuterTable to Vue 3 (Composition API) 
2. renamed RothCOuterTable to  RothCOuterContainer**

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
Hey , @YashKandalkar , kindly review the PR

**Comment by YashKandalkar** [comment]
Hey @thisiskaransgit, sorry for the late response!
The changes look good! Can you run `yarn lint --fix` and push again? The build seems to fail due to linting issues.

**Comment by thisiskaransgit** [comment]
hey @YashKandalkar ,kindly check

**Comment by YashKandalkar** [comment]
hey @thisiskaransgit thanks for the changes!
Can you please run `yarn lint --fix` and push again?

**Review by YashKandalkar — APPROVED** [review]
LGTM! @thisiskaransgit thanks for working on this! :rocket:

**Pull request merged**
