### PR TITLE
feat: add upload components for GCBM Simulation Run (WIP)

### PR DESCRIPTION
**Pull request by YashKandalkar**
## Description
Adds components for the upload section. WIP.

## Testing
go to /gcbm/upload/classifiers

## Additional Context (Please include any Screenshots/gifs if relevant)
image

### CODE REVIEW

**Comment by YashKandalkar** [comment]
https://user-images.githubusercontent.com/35102959/177055746-accb6a63-9786-41e3-8136-7c1b6b78d336.mp4

I actually love the [vue3-json-editor](https://github.com/joaomede/vue3-json-editor) library, it is extremely powerful (especially the Tree mode)! 
If anyone wants to test it, go [here](https://gcbm-editor-p3z2qhbi3-moja-global.vercel.app/gcbm/upload/classifiers), upload any file (validation isn't implemented yet) and click Upload. 

Click on Preview Config of any file, and go to the JSON Editor.

**Comment by YashKandalkar** [comment]
Progress so far: 
Added an indicator to show the active simulation, a confirmation for creating new simulation runs, GUI tab in config editor, vuex state persistence so the configs won't be lost on page reload.

https://user-images.githubusercontent.com/35102959/177210191-2e4aa5b1-742e-4830-96a3-2189ebe12cb3.mp4

**Comment by YashKandalkar** [comment]
Added this table for displaying table and column names.
As mentioned by @Namyalg and @padmajabhol, the table names and column names can be edited by the user.

image

image

image

image


I just realized we'd need some validations for these names too. I'll find the valid naming scheme for tables, and column names in relational dbs.

**Comment by YashKandalkar** [comment]
@HarshCasper I have a few more things to work on, I've written on my to-do list. For now, this can be reviewed and merged as it's already become huge.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
