### PR TITLE
feat: changed theme of GCBM Step1 2 as per new UI

### LINKED ISSUE #198: Bug:  Change colour theme of GCBM step 2 and step 3 as per new UI
### Describe the bug.

Color theme for GCBM step 2 and step 3 is not same as other pages of FLINT.UI

### Describe the steps to reproduce the behavior.

1. Go to the landing page of FLINT.UI
2. Click of Explore button for GCBM
3. Go to Upload dataset step
4. See the difference
5. Check the behavior for Run | Check status | Download step as well 

### Expected behavior.

UI color theme should be consistent across every page of the app. Please check the screenshots attached below to get idea about the expected colors. Please try to change the colors of GCBM steps 2 and 3 as per the GCBM step1.

### Screenshots.

Current colors 

GCBM step 2 
image

GCBM step 3
image

Expected colors (GCBM step 1)
image

### Operating Environment

Windows 10 - Chrome browser

### Additional Information

This behavior can be checked by going to http://localhost:8000/gcbm/run and http://localhost:8000/gcbm/upload as well while working in the local environment.

### PR DESCRIPTION
**Pull request by Palaksharma23**
# Pull Request Template

## Description

Fixes #198 

## Additional Context (Please include any Screenshots if relevant)

I have changed the theme of GCBM Step 1 2. 
I have also added navbar to both of them.
 
image
image
image
image

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar can you please take a look?

**Review by chicken-biryani — APPROVED** [review]

**Comment by Janvi-Thakkar** [comment]
LGTM! 

@Palaksharma23 can you please run these commands? 
git commit --amend --no-edit --signoff
git push --force-with-lease origin master

**Comment by Palaksharma23** [comment]
> LGTM!
> 
> @Palaksharma23 can you please run these commands? git commit --amend --no-edit --signoff git push --force-with-lease origin master

sure :)

**Comment by Palaksharma23** [comment]
Done :)

**Pull request merged**
